// Code generated by srpc-gen v0.0.1. DO NOT EDIT.

package main

import (
	"context"
	"github.com/tymbaca/srpc"
)

func NewEchoServiceClient(client *srpc.Client) *EchoServiceClient {
	return &EchoServiceClient{Client: client}
}

type EchoServiceClient struct {
	*srpc.Client
}

func (c *EchoServiceClient) Echo(ctx context.Context, req string) (resp string, err error) {
	err = c.Client.Call(ctx, "EchoService.Echo", req, &resp)
	return resp, err
}
