// Code generated by srpc-gen v0.1.0. DO NOT EDIT.

package main

import (
	"context"

	"github.com/tymbaca/srpc"
)

func NewMetadataServiceClient(client *srpc.Client) *MetadataServiceClient {
	return &MetadataServiceClient{Client: client}
}

type MetadataServiceClient struct {
	*srpc.Client
}

func (c *MetadataServiceClient) EchoMetadata(ctx context.Context, req Empty) (resp Empty, err error) {
	err = c.Client.Call(ctx, "MetadataService.EchoMetadata", req, &resp)
	return resp, err
}
