// Code generated by srpc-gen v0.1.0. Edit for your needs.

package main

import (
	"context"
	"fmt"

	"github.com/tymbaca/srpc"
	"github.com/tymbaca/srpc/metadata"
)

func NewMetadataServiceServer(
	s *srpc.Server,
) *MetadataServiceServer {
	svc := &MetadataServiceServer{
		Server: s,
	}

	srpc.Register[MetadataService](s, svc)

	return svc
}

type MetadataServiceServer struct {
	*srpc.Server
}

func (s *MetadataServiceServer) EchoMetadata(ctx context.Context, req Empty) (Empty, error) {
	md, _ := metadata.FromContext(ctx)
	fmt.Println("got md from client", md)

	// This is safe, when called here, [metadata.ResponseFromContext] always
	// returns valid pointer to response metadata.
	*metadata.ResponseFromContext(ctx) = md

	return Empty{}, nil
}
