// Code generated by srpc-gen v0.0.1. DO NOT EDIT.

package testdata

import (
	"context"
	"github.com/tymbaca/srpc"
)

func NewTestServiceClient(client *srpc.Client) *TestServiceClient {
	return &TestServiceClient{Client: client}
}

type TestServiceClient struct {
	*srpc.Client
}

func (c *TestServiceClient) Add(ctx context.Context, req AddReq) (resp AddResp, err error) {
	err = c.Client.Call(ctx, "TestService.Add", req, &resp)
	return resp, err
}

func (c *TestServiceClient) Divide(ctx context.Context, req DivideReq) (resp DivideResp, err error) {
	err = c.Client.Call(ctx, "TestService.Divide", req, &resp)
	return resp, err
}
