// Code generated by srpc-gen v0.1.0. DO NOT EDIT.

package testutil

import (
	"context"

	"github.com/tymbaca/srpc"
)

func NewTestServiceClient(client *srpc.Client) *TestServiceClient {
	return &TestServiceClient{Client: client}
}

type TestServiceClient struct {
	*srpc.Client
}

func (c *TestServiceClient) Add(ctx context.Context, req AddReq) (resp AddResp, err error) {
	err = c.Client.Call(ctx, "TestService.Add", req, &resp)
	return resp, err
}

func (c *TestServiceClient) Blob(ctx context.Context, req Blob) (resp Blob, err error) {
	err = c.Client.Call(ctx, "TestService.Blob", req, &resp)
	return resp, err
}

func (c *TestServiceClient) Divide(ctx context.Context, req DivideReq) (resp DivideResp, err error) {
	err = c.Client.Call(ctx, "TestService.Divide", req, &resp)
	return resp, err
}

func (c *TestServiceClient) LongAdd(ctx context.Context, req AddReq) (resp AddResp, err error) {
	err = c.Client.Call(ctx, "TestService.LongAdd", req, &resp)
	return resp, err
}

func (c *TestServiceClient) ReplyMD(ctx context.Context, req ReplyMDReq) (resp ReplyMDResp, err error) {
	err = c.Client.Call(ctx, "TestService.ReplyMD", req, &resp)
	return resp, err
}
