// Code generated by srpc-gen v0.0.1. Edit for your needs.

package testdata

import (
	"context"
	"errors"

	"github.com/tymbaca/srpc"
)

func NewTestServiceServer(s *srpc.Server) *TestServiceServer {
	svc := &TestServiceServer{
		Server: s,
	}

	srpc.Register[TestService](s, svc)

	return svc
}

type TestServiceServer struct {
	*srpc.Server
}

func (s *TestServiceServer) Add(ctx context.Context, req AddReq) (AddResp, error) {
	return AddResp{req.A + req.B}, nil
}

func (s *TestServiceServer) Divide(ctx context.Context, req DivideReq) (DivideResp, error) {
	if req.B == 0 {
		return DivideResp{}, errors.New("can't divide to 0")
	}

	return DivideResp{req.A / req.B}, nil
}
