// Code generated by srpc-gen v0.1.0. Edit for your needs.

package main

import (
	"context"
	"fmt"

	"github.com/tymbaca/srpc"
)

func NewEchoServiceServer(
	s *srpc.Server,
) *EchoServiceServer {
	svc := &EchoServiceServer{
		Server: s,
	}

	srpc.Register[EchoService](s, svc)

	return svc
}

type EchoServiceServer struct {
	*srpc.Server
}

func (s *EchoServiceServer) Echo(ctx context.Context, req string) (string, error) {
	fmt.Println("msg from client:", req)

	return "world", nil
}

func (s *EchoServiceServer) EchoStruct(ctx context.Context, req EchoStructReq) (EchoStructResp, error) {
	fmt.Println("msg from client:", req)

	return EchoStructResp{Val: "world"}, nil
}
