// Code generated by srpc-gen v0.0.1. DO NOT EDIT.

package testpackage

import (
	"context"

	"github.com/tymbaca/srpc"
)

func NewTestServiceClient(client *srpc.Client) *TestServiceClient {
	return &TestServiceClient{client: client}
}

type TestServiceClient struct {
	client *srpc.Client
}

func (c *TestServiceClient) Add(ctx context.Context, req testpackage.AddReq) (resp testpackage.AddResp, err error) {
	err = c.client.Call(ctx, "TestService.Add", req, &resp)
	return resp, err
}

func (c *TestServiceClient) Divide(ctx context.Context, req testpackage.DivideReq) (resp testpackage.DivideResp, err error) {
	err = c.client.Call(ctx, "TestService.Divide", req, &resp)
	return resp, err
}
