// Code generated by srpc-gen v0.0.1. DO NOT EDIT.

package testpackage

import (
	"context"

	"github.com/tymbaca/srpc"
	inner "github.com/tymbaca/srpc/cmd/testpackage/inner"
)

func NewTestService2Client(client *srpc.Client) *TestService2Client {
	return &TestService2Client{client: client}
}

type TestService2Client struct {
	client *srpc.Client
}

func (c *TestService2Client) Divide(ctx context.Context, req DivideReq) (resp DivideResp, err error) {
	err = c.client.Call(ctx, "TestService2.Divide", req, &resp)
	return resp, err
}

func (c *TestService2Client) Multiply(ctx context.Context, req inner.MultiplyReq) (resp inner.MultiplyResp, err error) {
	err = c.client.Call(ctx, "TestService2.Multiply", req, &resp)
	return resp, err
}
