// Code generated by srpc-gen v0.0.1. DO NOT EDIT.

package testpackage

import (
	"context"
)

type TestServiceServer struct {
	// TODO: fill
}

func (te *TestServiceServer) Add(ctx context.Context, req testpackage.AddReq) (testpackage.AddResp, error) {
	panic("not implemented") // TODO: Implement
}

func (te *TestServiceServer) Divide(ctx context.Context, req testpackage.DivideReq) (testpackage.DivideResp, error) {
	panic("not implemented") // TODO: Implement
}
