// Code generated by srpc-gen v0.0.1. DO NOT EDIT.

package testpackage

import (
	"context"
)

type TestService2Server struct {
	// TODO: fill
}

func (te *TestService2Server) Divide(ctx context.Context, req DivideReq) (DivideResp, error) {
	panic("not implemented") // TODO: Implement
}

func (te *TestService2Server) Multiply(ctx context.Context, req inner.MultiplyReq) (inner.MultiplyResp, error) {
	panic("not implemented") // TODO: Implement
}
