// Code generated by srpc-gen v0.0.1. Edit for your needs.

package testpackage

import (
	"context"
	"github.com/tymbaca/srpc/cmd/testpackage/inner"
)

type TestService2Server struct {
	// TODO: fill
}

func (s *TestService2Server) Divide(ctx context.Context, req DivideReq) (DivideResp, error) {
	panic("not implemented") // TODO: Implement
}

func (s *TestService2Server) Multiply(ctx context.Context, req inner.MultiplyReq) (inner.MultiplyResp, error) {
	panic("not implemented") // TODO: Implement
}
