// Code generated by srpc-gen v0.0.1. Edit for your needs.

package testpackage

import (
	"context"

	"github.com/tymbaca/srpc"
)

func NewTestServiceServer(codec srpc.Codec) *TestServiceServer {
	s := srpc.NewServer(codec)
	svc := &TestServiceServer{s}
	srpc.Register[TestService](s, svc)

	return svc
}

type TestServiceServer struct {
	*srpc.Server
}

func (s *TestServiceServer) Add(ctx context.Context, req AddReq) (AddResp, error) {
	panic("not implemented") // TODO: Implement
}

func (s *TestServiceServer) Divide(ctx context.Context, req DivideReq) (DivideResp, error) {
	panic("not implemented") // TODO: Implement
}
