// Code generated by srpc-gen v0.0.1. Edit for your needs.

package testpackage

import (
	"context"
)

type TestServiceServer struct {
	// TODO: fill
}

func (s *TestServiceServer) Add(ctx context.Context, req AddReq) (AddResp, error) {
	panic("not implemented") // TODO: Implement
}

func (s *TestServiceServer) Divide(ctx context.Context, req DivideReq) (DivideResp, error) {
	panic("not implemented") // TODO: Implement
}
