// Code generated by srpc-gen v0.0.1. Edit for your needs.
package testpackage

import (
	"context"

	"github.com/tymbaca/srpc"
)

func NewTestServiceExpServer(s *srpc.Server) *TestServiceExpServer {
	svc := &TestServiceExpServer{
		Server: s,
	}
	srpc.Register[TestService](s, svc)

	return svc
}

type TestServiceExpServer struct {
	*srpc.Server
}

func (s *TestServiceExpServer) Add(ctx context.Context, req AddReq) (AddResp, error) {
	panic("not implemented") // TODO: Implement
}

func (s *TestServiceExpServer) Divide(ctx context.Context, req DivideReq) (DivideResp, error) {
	panic("not implemented") // TODO: Implement
}
