// Code generated by srpc-gen v0.0.1. Edit for your needs.

package main

import (
	"context"

	"github.com/tymbaca/srpc"
	"github.com/tymbaca/srpc/cmd/tymbaca/inner"
)

// NOTE: this server file need to be edited after generation. Here you can fill
// your server logic, that handles each call.

func NewTestServiceServer(
	s *srpc.Server,
	// TODO: Fill
) *TestServiceServer {
	svc := &TestServiceServer{
		Server: s,
		// TODO: Fill
	}

	srpc.Register[TestService](s, svc)

	return svc
}

type TestServiceServer struct {
	*srpc.Server

	// TODO: Fill
}

func (s *TestServiceServer) Add(ctx context.Context, req AddReq) (AddResp, error) {
	panic("not implemented") // TODO: Implement
}

func (s *TestServiceServer) Divide(ctx context.Context, req DivideReq) (DivideResp, error) {
	panic("not implemented") // TODO: Implement
}

func (s *TestServiceServer) Multiply(ctx context.Context, req inner.MultiplyReq) (inner.MultiplyResp, error) {
	panic("not implemented") // TODO: Implement
}
