// Code generated by srpc-gen v0.0.1. DO NOT EDIT.

package main

import (
	"context"
	"github.com/tymbaca/srpc"
	"github.com/tymbaca/srpc/cmd/tymbaca/inner"
)

func NewTestServiceClient(client *srpc.Client) *TestServiceClient {
	return &TestServiceClient{client: client}
}

type TestServiceClient struct {
	client *srpc.Client
}

func (c *TestServiceClient) Add(ctx context.Context, req AddReq) (resp AddResp, err error) {
	err = c.client.Call(ctx, "TestService.Add", req, &resp)
	return resp, err
}

func (c *TestServiceClient) Divide(ctx context.Context, req DivideReq) (resp DivideResp, err error) {
	err = c.client.Call(ctx, "TestService.Divide", req, &resp)
	return resp, err
}

func (c *TestServiceClient) Multiply(ctx context.Context, req inner.MultiplyReq) (resp inner.MultiplyResp, err error) {
	err = c.client.Call(ctx, "TestService.Multiply", req, &resp)
	return resp, err
}
